name: GitAction

on:
  push:
    branches: ["main"] # main 브랜치에 push 이벤트가 발생하면
  pull_request:
    branches: ["main"] # main 브랜치에 pr 이벤트가 발생하면

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.15 

      - name: Build
        run: go build -v ./...

      # 도커 아이디와 토큰 설정하기
      - name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: havi98
          password: dckr_pat_2zVkGSsJHtJ7UfeDpKZVSrZx-vA
          
      - name: build and release to DockerHub
        env:
          NAME: havi98
          REPO: goapplication
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
